# Site settings
title: dmillerart
email: duncanemiller@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Duncan Miller - Art Portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dmillerart.github.io/" # the base hostname & protocol for your site
twitter_username: fakename
github_username:  fakename
instagram_username: fakename

# Build settings
markdown: kramdown
permalink: pretty
